global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'tu-mail@gmail.com'
  smtp_auth_username: 'tu-mail@gmail.com'
  smtp_auth_password: 'TU_APP_PASSWORD'

route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  receiver: 'team-email'

receivers:
  - name: 'team-email'
    email_configs:
      - to: 'destino@ejemplo.com'
        send_resolved: true
