global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "/etc/prometheus/rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['node_exporter:9100']

  - job_name: 'mysql_exporter'
    static_configs:
      - targets: ['mysqld_exporter:9104']

  - job_name: 'nginx_exporter'
    static_configs:
      - targets: ['nginx_exporter:9113']

  - job_name: 'apps'
    metrics_path: /metrics
    static_configs:
      - targets: ['app1:5000', 'app2:5000']

  - job_name: 'flask_app'
    metrics_path: /metrics
    static_configs:
    - targets: ['app1:5000', 'app2:5000']

